---
- hosts: localhost
  gather_facts: False
  tasks:
    - name: Generating an SSH keypair
      openssh_keypair:
        path: "{{ lookup('env', 'TKS_BP_V_PROXMOX_SSH_KEY') | default('~/.ssh/TKS') }}"
        type: ed25519
      when:
        - lookup('env', 'TKS_BP_R_CREATE_USER_ACCOUNT') == 'true'


- hosts: proxmox
  gather_facts: False
  vars: 
    SSH_KEY: "{{ lookup('env', 'TKS_BP_V_PROXMOX_SSH_KEY') | default('~/.ssh/TKS') }}"
    USER_ACCOUNT: "{{ lookup('env', 'TKS_BP_V_PROXMOX_USER_NAME') | default('tks') }}"
  tasks:
    - import_role: 
        name: Create_User_Account
      when:
        - lookup('env', 'TKS_BP_R_CREATE_USER_ACCOUNT') == 'true'
